name: CI

on: [push]

jobs:
  tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Homebrew
        run: |
          brew update
          HOMEBREW_TAP_DIR="/usr/local/Homebrew/Library/Taps/galderz/homebrew-tap"
          mkdir -p "$HOMEBREW_TAP_DIR"
          rm -rf "$HOMEBREW_TAP_DIR"
          ln -s "$PWD" "$HOMEBREW_TAP_DIR"
      - name: Run brew style
        run: brew style galderz/tap
      - name: Run brew test-bot
        run: |
          brew test-bot
